//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.BookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestClient.BookService.PaperBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestClient.BookService.EBook))]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Category[] CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Writer[] WriterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Category[] Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalTitle {
            get {
                return this.OriginalTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalTitleField, value) != true)) {
                    this.OriginalTitleField = value;
                    this.RaisePropertyChanged("OriginalTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Writer[] Writer {
            get {
                return this.WriterField;
            }
            set {
                if ((object.ReferenceEquals(this.WriterField, value) != true)) {
                    this.WriterField = value;
                    this.RaisePropertyChanged("Writer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaperBook", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PaperBook : TestClient.BookService.Book {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookItem[] CopiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookItem[] Copies {
            get {
                return this.CopiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CopiesField, value) != true)) {
                    this.CopiesField = value;
                    this.RaisePropertyChanged("Copies");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBook", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EBook : TestClient.BookService.Book {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DownloadableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Downloadable {
            get {
                return this.DownloadableField;
            }
            set {
                if ((this.DownloadableField.Equals(value) != true)) {
                    this.DownloadableField = value;
                    this.RaisePropertyChanged("Downloadable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Book[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Category[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Category ParentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Book[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Category[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Category Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Writer", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Writer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Book[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Book[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookItem", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BookItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.PaperBook BookDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookStateEntry[] BookStateEntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BoughtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookCondition ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookStates CurrentStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.PaperBook BookData {
            get {
                return this.BookDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BookDataField, value) != true)) {
                    this.BookDataField = value;
                    this.RaisePropertyChanged("BookData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookStateEntry[] BookStateEntries {
            get {
                return this.BookStateEntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookStateEntriesField, value) != true)) {
                    this.BookStateEntriesField = value;
                    this.RaisePropertyChanged("BookStateEntries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Bought {
            get {
                return this.BoughtField;
            }
            set {
                if ((this.BoughtField.Equals(value) != true)) {
                    this.BoughtField = value;
                    this.RaisePropertyChanged("Bought");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookCondition Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((this.ConditionField.Equals(value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookStates CurrentState {
            get {
                return this.CurrentStateField;
            }
            set {
                if ((this.CurrentStateField.Equals(value) != true)) {
                    this.CurrentStateField = value;
                    this.RaisePropertyChanged("CurrentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookStateEntry", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BookStateEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookItem BookItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Member MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookStateEntryType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookItem BookItem {
            get {
                return this.BookItemField;
            }
            set {
                if ((object.ReferenceEquals(this.BookItemField, value) != true)) {
                    this.BookItemField = value;
                    this.RaisePropertyChanged("BookItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Member Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookStateEntryType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookCondition", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities")]
    public enum BookCondition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bad = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryBad = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookStates", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities")]
    public enum BookStates : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Free = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.BookStateEntry[] BookStatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.BookStateEntry[] BookStates {
            get {
                return this.BookStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookStatesField, value) != true)) {
                    this.BookStatesField = value;
                    this.RaisePropertyChanged("BookStates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((this.RegistrationField.Equals(value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookStateEntryType", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Entities")]
    public enum BookStateEntryType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Borrow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Back = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Service", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestClient.BookService.SaveMemberResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveMemberResponse", Namespace="http://schemas.datacontract.org/2004/07/BookDatabase.Service", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SaveMemberResponse : TestClient.BookService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestClient.BookService.Member MemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestClient.BookService.Member Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookService.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBook", ReplyAction="http://tempuri.org/IBookService/GetAllBookResponse")]
        TestClient.BookService.Book[] GetAllBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBook", ReplyAction="http://tempuri.org/IBookService/GetAllBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.Book[]> GetAllBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllPaperBook", ReplyAction="http://tempuri.org/IBookService/GetAllPaperBookResponse")]
        TestClient.BookService.PaperBook[] GetAllPaperBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllPaperBook", ReplyAction="http://tempuri.org/IBookService/GetAllPaperBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.PaperBook[]> GetAllPaperBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllEBook", ReplyAction="http://tempuri.org/IBookService/GetAllEBookResponse")]
        TestClient.BookService.EBook[] GetAllEBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllEBook", ReplyAction="http://tempuri.org/IBookService/GetAllEBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.EBook[]> GetAllEBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBookById", ReplyAction="http://tempuri.org/IBookService/GetBookByIdResponse")]
        TestClient.BookService.Book GetBookById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBookById", ReplyAction="http://tempuri.org/IBookService/GetBookByIdResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.Book> GetBookByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        TestClient.BookService.Book[] SearchBook(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.Book[]> SearchBookAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/LendBook", ReplyAction="http://tempuri.org/IBookService/LendBookResponse")]
        TestClient.BookService.ResponseBase LendBook(string bookId, string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/LendBook", ReplyAction="http://tempuri.org/IBookService/LendBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.ResponseBase> LendBookAsync(string bookId, string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BackBook", ReplyAction="http://tempuri.org/IBookService/BackBookResponse")]
        TestClient.BookService.ResponseBase BackBook(string bookId, string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BackBook", ReplyAction="http://tempuri.org/IBookService/BackBookResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.ResponseBase> BackBookAsync(string bookId, string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SaveBook", ReplyAction="http://tempuri.org/IBookService/SaveBookResponse")]
        void SaveBook(TestClient.BookService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SaveBook", ReplyAction="http://tempuri.org/IBookService/SaveBookResponse")]
        System.Threading.Tasks.Task SaveBookAsync(TestClient.BookService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchMember", ReplyAction="http://tempuri.org/IBookService/SearchMemberResponse")]
        TestClient.BookService.Member[] SearchMember(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchMember", ReplyAction="http://tempuri.org/IBookService/SearchMemberResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.Member[]> SearchMemberAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SaveMember", ReplyAction="http://tempuri.org/IBookService/SaveMemberResponse")]
        TestClient.BookService.SaveMemberResponse SaveMember(TestClient.BookService.Member member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SaveMember", ReplyAction="http://tempuri.org/IBookService/SaveMemberResponse")]
        System.Threading.Tasks.Task<TestClient.BookService.SaveMemberResponse> SaveMemberAsync(TestClient.BookService.Member member);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : TestClient.BookService.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<TestClient.BookService.IBookService>, TestClient.BookService.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestClient.BookService.Book[] GetAllBook() {
            return base.Channel.GetAllBook();
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.Book[]> GetAllBookAsync() {
            return base.Channel.GetAllBookAsync();
        }
        
        public TestClient.BookService.PaperBook[] GetAllPaperBook() {
            return base.Channel.GetAllPaperBook();
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.PaperBook[]> GetAllPaperBookAsync() {
            return base.Channel.GetAllPaperBookAsync();
        }
        
        public TestClient.BookService.EBook[] GetAllEBook() {
            return base.Channel.GetAllEBook();
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.EBook[]> GetAllEBookAsync() {
            return base.Channel.GetAllEBookAsync();
        }
        
        public TestClient.BookService.Book GetBookById(int id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.Book> GetBookByIdAsync(int id) {
            return base.Channel.GetBookByIdAsync(id);
        }
        
        public TestClient.BookService.Book[] SearchBook(string key) {
            return base.Channel.SearchBook(key);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.Book[]> SearchBookAsync(string key) {
            return base.Channel.SearchBookAsync(key);
        }
        
        public TestClient.BookService.ResponseBase LendBook(string bookId, string memberId) {
            return base.Channel.LendBook(bookId, memberId);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.ResponseBase> LendBookAsync(string bookId, string memberId) {
            return base.Channel.LendBookAsync(bookId, memberId);
        }
        
        public TestClient.BookService.ResponseBase BackBook(string bookId, string memberId) {
            return base.Channel.BackBook(bookId, memberId);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.ResponseBase> BackBookAsync(string bookId, string memberId) {
            return base.Channel.BackBookAsync(bookId, memberId);
        }
        
        public void SaveBook(TestClient.BookService.Book book) {
            base.Channel.SaveBook(book);
        }
        
        public System.Threading.Tasks.Task SaveBookAsync(TestClient.BookService.Book book) {
            return base.Channel.SaveBookAsync(book);
        }
        
        public TestClient.BookService.Member[] SearchMember(string key) {
            return base.Channel.SearchMember(key);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.Member[]> SearchMemberAsync(string key) {
            return base.Channel.SearchMemberAsync(key);
        }
        
        public TestClient.BookService.SaveMemberResponse SaveMember(TestClient.BookService.Member member) {
            return base.Channel.SaveMember(member);
        }
        
        public System.Threading.Tasks.Task<TestClient.BookService.SaveMemberResponse> SaveMemberAsync(TestClient.BookService.Member member) {
            return base.Channel.SaveMemberAsync(member);
        }
    }
}
